#CI项目
name: IMM-ROCKCHIP

#CI计划
on:
  #自动触发，详见 GitHub文档：关于触发工作流的事件
  #  ┌───────────── minute (0 - 59)
  #  │ ┌───────────── hour (0 - 23)
  #  │ │ ┌───────────── day of the month (1 - 31)
  #  │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #  │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #  │ │ │ │ │
  #  │ │ │ │ │
  #  │ │ │ │ │
  #  * * * * *
  #--分时日月周 
  #自动编译：每周2,4,6早上6点(UTC 22:00) --分 时 日 月 周
  #- cron: 0 22 * * 2,4,6
  schedule:
    - cron: 0 22 * * 2,4,6
  #手动编译
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，仅限一个。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'
        required: false
        type: boolean

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: ${{matrix.TARGET}}
    strategy:
      fail-fast: false
      #max-parallel: 3
      matrix:
        TARGET: [Rockchip]
        SOURCE: [immortalwrt/immortalwrt]
        BRANCH: [openwrt-23.05]

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译平台
      WRT_TARGET: ${{matrix.TARGET}}
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: ImmortalWrt
      #默认WIFI名
      WRT_WIFI: OWRT
      #默认地址
      WRT_IP: 192.168.2.1
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #源码链接
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      #源码分支
      WRT_BRANCH: ${{matrix.BRANCH || 'master'}}
      #源码名称
      WRT_SOURCE: ${{matrix.SOURCE}}
      #仅输出配置文件
      WRT_TEST: ${{inputs.TEST}}
